<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.1.3" />
		<PackageReference Include="Gridify" Version="2.16.3" />
		<PackageReference Include="Gridify.EntityFramework" Version="2.16.3" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.20" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Invoice.Domain\Invoice.Domain.csproj" />
    <ProjectReference Include="..\Invoice.Framework\Invoice.Framework.csproj" />
    <ProjectReference Include="..\Invoice.Infrastructure\Invoice.Infrastructure.csproj" />
  </ItemGroup>

</Project>
